name: Build and deploy to Github Pages
# 注意，GitHub Pages 在设置配置，因此你无需编辑这个文件

on:
  # 对推送至默认分支的操作运行
  push:
    branches: ["main"]

  # 允许您从“操作”选项卡手动运行此工作流程。
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在进行的运行和最新排队的运行之间的排队运行。
# 但是，请勿取消正在进行的运行，因为我们希望这些生产部署能够完成。
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 由于我们只是进行部署，所以只执行一次部署任务。
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Build and deploy to Github Pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm ci --no-frozen-lockfile || pnpm install
        
      - name: Build docs
        run: pnpm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传仅dist文件夹的文件
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
